[project]
name = "model"
version = "0.1.0"
description = "Train model weights using scripts provided here."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "emoji>=2.15.0",
    "google-api-python-client>=2.200.0",
    "openai>=3.5.0",
    "pandas>=3.0.5",
    "requests>=2.34.2",
    "scikit-learn>=1.9.0",
    "sentence-transformers>=6.0.0",
    "tqdm>=4.70.0",
]
